package com.AppAnalytics.models;



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.CreationTimestamp;

/**
 * TblMail generated by hbm2java
 */
@Entity
@Table(name = "tbl_mail", catalog = "appanalytics", uniqueConstraints = @UniqueConstraint(columnNames = "TOKEN"))
public class TblMail implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer mailId;
	private String token;
	private String email;
	private boolean isLatest;
	private Date expirationDate;
	private Date recInsDt;
	private Date recLastUpdDt;
	private int recInsUsrid;
	private Integer recLastUpdUsrid;

	public TblMail() {
	}

	public TblMail(String token, String email, boolean isLatest, Date expirationDate,int recInsUsrid) {
		this.token = token;
		this.email = email;
		this.isLatest = isLatest;
		this.expirationDate = expirationDate;
		this.recInsUsrid = recInsUsrid;
	}

	public TblMail(String token, String email, boolean isLatest, Date expirationDate,
			Date recInsDt, Date recLastUpdDt, int recInsUsrid,
			Integer recLastUpdUsrid) {
		this.token = token;
		this.email = email;
		this.isLatest = isLatest;
		this.expirationDate = expirationDate;
		this.recInsDt = recInsDt;
		this.recLastUpdDt = recLastUpdDt;
		this.recInsUsrid = recInsUsrid;
		this.recLastUpdUsrid = recLastUpdUsrid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MAIL_ID", unique = true, nullable = false)
	public Integer getMailId() {
		return this.mailId;
	}

	public void setMailId(Integer mailId) {
		this.mailId = mailId;
	}

	@Column(name = "TOKEN", unique = true, nullable = false, length = 100)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}
	
	@Column(name = "EMAIL", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "IS_LATEST", nullable = false)
	public boolean isIsLatest() {
		return this.isLatest;
	}

	public void setIsLatest(boolean isLatest) {
		this.isLatest = isLatest;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EXPIRATION_DATE", nullable = false, length = 19)
	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REC_INS_DT", length = 19, updatable = false)
	public Date getRecInsDt() {
		return this.recInsDt;
	}

	public void setRecInsDt(Date recInsDt) {
		this.recInsDt = recInsDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REC_LAST_UPD_DT", length = 19)
	public Date getRecLastUpdDt() {
		return this.recLastUpdDt;
	}

	public void setRecLastUpdDt(Date recLastUpdDt) {
		this.recLastUpdDt = recLastUpdDt;
	}

	@Column(name = "REC_INS_USRID", nullable = false, updatable = false)
	public int getRecInsUsrid() {
		return this.recInsUsrid;
	}

	public void setRecInsUsrid(int recInsUsrid) {
		this.recInsUsrid = recInsUsrid;
	}

	@Column(name = "REC_LAST_UPD_USRID")
	public Integer getRecLastUpdUsrid() {
		return this.recLastUpdUsrid;
	}

	public void setRecLastUpdUsrid(Integer recLastUpdUsrid) {
		this.recLastUpdUsrid = recLastUpdUsrid;
	}

}
