package com.AppAnalytics.models;


//Generated Nov 15, 2016 2:36:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;

/**
* TblOauthAccessTokens generated by hbm2java
*/
@Entity
@Table(name = "tbl_oauth_access_tokens", catalog = "SG")
public class TblOauthAccessTokens implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private String accessToken;
	private String clientId;
	private Date expirationTime;
	private int credentialsId;
	private Date recInsDt;
	private Date recLastUpdDt;
	private int recInsUsrid;
	private Integer recLastUpdUsrid;

	public TblOauthAccessTokens() {
	}

	public TblOauthAccessTokens(String accessToken, String clientId,
			Date expirationTime, int credentialsId, Date recInsDt,
			int recInsUsrid) {
		this.accessToken = accessToken;
		this.clientId = clientId;
		this.expirationTime = expirationTime;
		this.credentialsId = credentialsId;
		this.recInsDt = recInsDt;
		this.recInsUsrid = recInsUsrid;
	}

	public TblOauthAccessTokens(String accessToken, String clientId,
			Date expirationTime, int credentialsId, Date recInsDt,
			Date recLastUpdDt, int recInsUsrid, Integer recLastUpdUsrid) {
		this.accessToken = accessToken;
		this.clientId = clientId;
		this.expirationTime = expirationTime;
		this.credentialsId = credentialsId;
		this.recInsDt = recInsDt;
		this.recLastUpdDt = recLastUpdDt;
		this.recInsUsrid = recInsUsrid;
		this.recLastUpdUsrid = recLastUpdUsrid;
	}

	
	@Id
	@Column(name = "ACCESS_TOKEN", unique = true, nullable = false, length = 100)
	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	@Column(name = "CLIENT_ID", nullable = false, length = 100)
	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EXPIRATION_TIME", nullable = false, length = 19)
	public Date getExpirationTime() {
		return this.expirationTime;
	}

	public void setExpirationTime(Date expirationTime) {
		this.expirationTime = expirationTime;
	}

	@Column(name = "CREDENTIALS_ID", nullable = false)
	public int getCredentialsId() {
		return this.credentialsId;
	}

	public void setCredentialsId(int credentialsId) {
		this.credentialsId = credentialsId;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REC_INS_DT", length = 19, updatable = false)
	public Date getRecInsDt() {
		return this.recInsDt;
	}

	public void setRecInsDt(Date recInsDt) {
		this.recInsDt = recInsDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REC_LAST_UPD_DT", length = 19)
	public Date getRecLastUpdDt() {
		return this.recLastUpdDt;
	}

	public void setRecLastUpdDt(Date recLastUpdDt) {
		this.recLastUpdDt = recLastUpdDt;
	}

	@Column(name = "REC_INS_USRID", nullable = false, updatable = false)
	public int getRecInsUsrid() {
		return this.recInsUsrid;
	}

	public void setRecInsUsrid(int recInsUsrid) {
		this.recInsUsrid = recInsUsrid;
	}

	@Column(name = "REC_LAST_UPD_USRID")
	public Integer getRecLastUpdUsrid() {
		return this.recLastUpdUsrid;
	}

	public void setRecLastUpdUsrid(Integer recLastUpdUsrid) {
		this.recLastUpdUsrid = recLastUpdUsrid;
	}

}
