package com.AppAnalytics.models;

// Generated Nov 15, 2016 2:36:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigInteger;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.DynamicUpdate;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TblUserCredentials generated by hbm2java
 */
@Entity
@Table(name = "tbl_user_credentials", catalog = "appanalytics", uniqueConstraints = {
		@UniqueConstraint(columnNames = "EMAIL"),
		@UniqueConstraint(columnNames = "USERNAME") })
@DynamicUpdate(value = true)
public class TblUserCredentials implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer credentialsId;
	private BigInteger facebookId;
	private BigInteger twitterId;
	private String googleId;
	private String userName;
	private String email;
	private String mobileNumber;
	private String password;
	private String salt;
	private Boolean isActive;
	private Boolean emailVerified;
	private Boolean termsOfUse;
	private int userId;
	private Date recInsDt;
	private Date recLastUpdDt;
	private Integer recInsUsrid;
	private Integer recLastUpdUsrid;



//	--- Mapping Variables ---
//	private TblUserProfile userProfile;

	//--- User Defined Variables ---
	@Transient
	private String firstName;
	@Transient
	private String lastName;
	
	@Transient
	private String gender;
	
	@Transient	
	private String token;
	@Transient
	private String oldPassword;
	@Transient
	private List<Integer> credentialsIdList;
	@Transient
	private String gRecaptchaResponse; 
	@Transient
	private Boolean isAdmin;
	//private TblAddress address;
	@Transient
	private String zipCode;
	@Transient
	private String subject;
	@Transient
	private String message;
	@Transient
	private String compaignUrl;
	@Transient
	private String userType;


	public TblUserCredentials() {
	}

	public TblUserCredentials(String userName, Integer credentialsId, Integer userId) {
		this.userName = userName;
		this.credentialsId = credentialsId;
		this.userId = userId;
	}

	public TblUserCredentials(String userName, String email, String password,
			String salt, boolean isActive, boolean emailVerified,
			boolean termsOfUse, int userId, Date recInsDt) {
		this.userName = userName;
		this.email = email;
		this.password = password;
		this.salt = salt;
		this.isActive = isActive;
		this.emailVerified = emailVerified;
		this.termsOfUse = termsOfUse;
		this.userId = userId;
		this.recInsDt = recInsDt;
	}

	public TblUserCredentials(String userName, String email, String password,
			String salt, Boolean isActive, boolean emailVerified,
			boolean termsOfUse, int userId, Date recInsDt, Date recLastUpdDt,
			Integer recInsUsrid, Integer recLastUpdUsrid) {
		this.userName = userName;
		this.email = email;
		this.password = password;
		this.salt = salt;
		this.isActive = isActive;
		this.emailVerified = emailVerified;
		this.termsOfUse = termsOfUse;
		this.userId = userId;
		this.recInsDt = recInsDt;
		this.recLastUpdDt = recLastUpdDt;
		this.recInsUsrid = recInsUsrid;
		this.recLastUpdUsrid = recLastUpdUsrid;
	}

	public TblUserCredentials(String userName, String email, String password,String googleId,
			String firstName, String lastName, boolean termsOfUse,boolean isAdmin) {
		this.userName = userName;
		this.email = email;
		this.password = password;
		this.googleId = googleId;
//		this.firstName = firstName;
	//	this.lastName = lastName;
		this.termsOfUse = termsOfUse;
		//this.isAdmin = isAdmin;
	}

	public TblUserCredentials(String userName, String firstName,
			String lastName, String email, String password,
			BigInteger facebookId) {
		this.userName = userName;
		this.email = email;
		this.password = password;
		//this.firstName = firstName;
		//this.lastName = lastName;
		this.facebookId = facebookId;
	}

	public TblUserCredentials(BigInteger facebookId, String userName, String email,
			String password, boolean termsOfUse, boolean isAdmin) {
		this.facebookId = facebookId;
		this.userName = userName;
		this.email = email;
		this.password = password;
		this.termsOfUse = termsOfUse;
		//this.isAdmin = isAdmin;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CREDENTIAL_ID", unique = true, nullable = false)
	public Integer getCredentialsId() {
		return this.credentialsId;
	}

	public void setCredentialsId(Integer credentialsId) {
		this.credentialsId = credentialsId;
	}

	@Column(name = "USERNAME", unique = true, nullable = false, length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "EMAIL", unique = true, nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PASSWORD", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "SALT", nullable = false, length = 45)
	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	@Column(name = "IS_ACTIVE")
	public Boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "EMAIL_VERIFIED")
	public Boolean isEmailVerified() {
		return this.emailVerified;
	}

	public void setEmailVerified(Boolean emailVerified) {
		this.emailVerified = emailVerified;
	}

	@Column(name = "TERMS_OF_USE")
	public Boolean isTermsOfUse() {
		return this.termsOfUse;
	}

	public void setTermsOfUse(Boolean termsOfUse) {
		this.termsOfUse = termsOfUse;
	}

	@Column(name = "USER_ID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REC_INS_DT", length = 19, updatable = false)
	public Date getRecInsDt() {
		return this.recInsDt;
	}

	public void setRecInsDt(Date recInsDt) {
		this.recInsDt = recInsDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REC_LAST_UPD_DT", length = 19)
	public Date getRecLastUpdDt() {
		return this.recLastUpdDt;
	}

	public void setRecLastUpdDt(Date recLastUpdDt) {
		this.recLastUpdDt = recLastUpdDt;
	}

	@Column(name = "REC_INS_USR_ID", updatable = false)
	public Integer getRecInsUsrid() {
		return this.recInsUsrid;
	}

	public void setRecInsUsrid(Integer recInsUsrid) {
		this.recInsUsrid = recInsUsrid;
	}

	@Column(name = "REC_LAST_UPD_ID")
	public Integer getRecLastUpdUsrid() {
		return this.recLastUpdUsrid;
	}

	public void setRecLastUpdUsrid(Integer recLastUpdUsrid) {
		this.recLastUpdUsrid = recLastUpdUsrid;
	}

	@Column(name = "FACEBOOK_ID")
	public BigInteger getFacebookId() {
		return facebookId;
	}

	public void setFacebookId(BigInteger facebookId) {
		this.facebookId = facebookId;
	}

	@Column(name = "TWITTER_ID")
	public BigInteger getTwitterId() {
		return twitterId;
	}

	public void setTwitterId(BigInteger twitterId) {
		this.twitterId = twitterId;
	}
	
	//@Column(name = "GOOGLE_ID")
	@Transient
	  public String getGoogleId() {
		return googleId;
	}

	public void setGoogleId(String googleId) {
		this.googleId = googleId;
	}

	@Column(name = "MOBILE_NUMBER")
	public String getMobileNumber() {
		return mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	/*public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public String getOldPassword() {
		return oldPassword;
	}

	public void setOldPassword(String oldPassword) {
		this.oldPassword = oldPassword;
	}

	public String getgRecaptchaResponse() {
		return gRecaptchaResponse;
	}

	public void setgRecaptchaResponse(String gRecaptchaResponse) {
		this.gRecaptchaResponse = gRecaptchaResponse;
	}

	public Boolean getIsAdmin() {
		return isAdmin;
	}

	public void setIsAdmin(Boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}
*/
	
	@Transient
	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}
	//--- Getter Setter for Mapping POJO ---
	TblUserProfile userProfile;
	/*@JsonBackReference
	@OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "USER_ID", insertable = false, updatable = false)
	@JsonManagedReference*/
	@Transient
	public TblUserProfile getUserProfile() {
		return userProfile;
	}

	public void setUserProfile(TblUserProfile userProfile) {
		this.userProfile = userProfile;
	}

	//--- Getter Setter for User Defined Variables ---
	@Transient
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Transient
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Transient
	public List<Integer> getCredentialsIdList() {
		return credentialsIdList;
	}

	public void setCredentialsIdList(List<Integer> credentialsIdList) {
		this.credentialsIdList = credentialsIdList;
	}

	@Transient
	public String getOldPassword() {
		return oldPassword;
	}

	public void setOldPassword(String oldPassword) {
		this.oldPassword = oldPassword;
	}

	@Transient
	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Transient
	public String getgRecaptchaResponse() {
		return gRecaptchaResponse;
	}

	public void setgRecaptchaResponse(String gRecaptchaResponse) {
		this.gRecaptchaResponse = gRecaptchaResponse;
	}

	@Transient
	public Boolean getIsAdmin() {
		return isAdmin;
	}

	public void setIsAdmin(Boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	

	@Transient
	public String getZipCode() {
		return zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Transient
	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Transient
	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Transient
	public String getCompaignUrl() {
		return compaignUrl;
	}

	public void setCompaignUrl(String compaignUrl) {
		this.compaignUrl = compaignUrl;
	}

	@Transient
	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

}
